### PR TITLE
Use Spiffworkflow-Proxy Library

### PR DESCRIPTION
**Pull request by danfunk**
use the Spiff Connector blueprint for all business logic.   This repo is now just a shell that just contains the dependencies specific to status.

Please see https://github.com/sartography/spiffworkflow-proxy -- where I have copied ll of @jbirddog's code so I can take credit for it.

### CODE REVIEW

**Comment by danfunk** [comment]
looks like I must have missed pulling down before doing the change over ...

**Comment by danfunk** [comment]
Damn, I don't like the name. hold on.

**Review by jbirddog — APPROVED** [review]
Very cool.

**Comment by burnettk** [comment]
and...all the code is shared, bam.

**Review by burnettk — APPROVED** [review]

**Pull request merged**
